### ISSUE TITLE
I know I'm not to savvy when it comes to this tech ,but why not create the 1inch token to handle micro payments and create it to become deflationary. With the total amount of token that you currently have this would Increase the value of the token. you can have the token burned from the total supply everytime we earn rewards we also burn a certain amount of satoshis. Again I'm really sorry for my novice opinion but i really like this project and believe it will do well.

### ISSUE THREAD

**Issue by morales622** [1inch/1IPs#20]
1ip: 1
title: 1inch Liquidity Proposal concepts and terminologies
status: Draft
type: Information
author: 1inch Network team
created: 2020-12-25

---

In this very first 1IP, we formally define the core concepts and terminologies of 1inch Government to set a common ground for 1inch community. The definitions here will be used as the truth (not assumption) in every discussion of the DAO.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by skywinder** [comment]
Please, follow guidelines, when filling 1IP.
